# exemplo de como dar deploy no github pages usando github actions
# esse arquivo vai dentro do seu repositorio em .github/workflows/blabla.yml
# Creditos: Caio Peternela, aluno do buser tech (chupinhei daqui)
# https://github.com/caiopeternela/pylifeandvuelife/blob/dev/.github/workflows/ci.yml

name: publica no ghpages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist
